<?php

declare(strict_types=1);

$root = __DIR__;
$uriPath = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?: '/';
$filePath = realpath($root . $uriPath);

if ($filePath !== false && str_starts_with($filePath, $root) && is_file($filePath)) {
    return false;
}

if (preg_match('#^/api(?:/.*)?$#', $uriPath) === 1) {
    require $root . '/api/index.php';
    return true;
}

if ($uriPath === '/admin' || $uriPath === '/admin/') {
    require $root . '/admin/index.php';
    return true;
}

// robots.txt, sitemap.xml and llms.txt are generated by PHP in production
// (see .htaccess); serve them the same way here so dev matches.
$generated = [
    '/robots.txt' => '/robots.php',
    '/sitemap.xml' => '/sitemap.php',
    '/llms.txt' => '/llms.php',
];
if (isset($generated[$uriPath])) {
    require $root . $generated[$uriPath];
    return true;
}

if ($uriPath === '/' || $uriPath === '') {
    require $root . '/index.php';
    return true;
}

if (preg_match('#^/(en|fr|nl|it|tr)/?$#', $uriPath) === 1) {
    require $root . '/index.php';
    return true;
}

// Blog: archive plus one template resolved by slug, mirroring .htaccess.
if (preg_match('#^/(?:(?:en|fr|nl|it|tr)/)?blog/?$#', $uriPath) === 1) {
    require $root . '/blog.php';
    return true;
}
if (preg_match('#^/(?:(?:en|fr|nl|it|tr)/)?blog/([a-z0-9-]+)/?$#', $uriPath, $m) === 1) {
    $_GET['slug'] = $m[1];
    require $root . '/blog-post.php';
    return true;
}

if (preg_match('#^/(?:(?:en|fr|nl|it|tr)/)?consult/?$#', $uriPath) === 1) {
    $originalQuery = parse_url($_SERVER['REQUEST_URI'] ?? '', PHP_URL_QUERY);
    $target = '/?open=consult';
    if (is_string($originalQuery) && $originalQuery !== '') {
        $target .= '&' . $originalQuery;
    }
    header('Location: ' . $target, true, 302);
    return true;
}

if (preg_match('#^/(?:(?:en|fr|nl|it|tr)/)?consult-light/?$#', $uriPath) === 1) {
    $originalQuery = parse_url($_SERVER['REQUEST_URI'] ?? '', PHP_URL_QUERY);
    $target = '/?open=consult-light';
    if (is_string($originalQuery) && $originalQuery !== '') {
        $target .= '&' . $originalQuery;
    }
    header('Location: ' . $target, true, 302);
    return true;
}

$trimmed = trim($uriPath, '/');
// /<lang>/<page> serves the same template; includes/i18n.php reads the
// language back off the URL, so the prefix only needs stripping to find the
// file on disk.
$trimmed = (string) preg_replace('#^(?:en|fr|nl|it|tr)/#', '', $trimmed);
if ($trimmed !== '' && preg_match('/^[A-Za-z0-9-]+$/', $trimmed) === 1) {
    $phpPage = $root . '/' . $trimmed . '.php';
    if (is_file($phpPage)) {
        require $phpPage;
        return true;
    }
}

// Mirrors the ErrorDocument rule in .htaccess.
require $root . '/404.php';
return true;
