<?php

declare(strict_types=1);

$root = __DIR__;
$uriPath = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?: '/';
$filePath = realpath($root . $uriPath);

if ($filePath !== false && str_starts_with($filePath, $root) && is_file($filePath)) {
    return false;
}

if (preg_match('#^/api(?:/.*)?$#', $uriPath) === 1) {
    require $root . '/api/index.php';
    return true;
}

if ($uriPath === '/admin' || $uriPath === '/admin/') {
    require $root . '/admin/index.php';
    return true;
}

// robots.txt, sitemap.xml and llms.txt are generated by PHP in production
// (see .htaccess); serve them the same way here so dev matches.
$generated = [
    '/robots.txt' => '/robots.php',
    '/sitemap.xml' => '/sitemap.php',
    '/llms.txt' => '/llms.php',
];
if (isset($generated[$uriPath])) {
    require $root . $generated[$uriPath];
    return true;
}

if ($uriPath === '/' || $uriPath === '') {
    require $root . '/index.php';
    return true;
}

if ($uriPath === '/en' || $uriPath === '/en/') {
    require $root . '/index.php';
    return true;
}

if ($uriPath === '/consult' || $uriPath === '/consult/' || $uriPath === '/en/consult' || $uriPath === '/en/consult/') {
    $originalQuery = parse_url($_SERVER['REQUEST_URI'] ?? '', PHP_URL_QUERY);
    $target = '/?open=consult';
    if (is_string($originalQuery) && $originalQuery !== '') {
        $target .= '&' . $originalQuery;
    }
    header('Location: ' . $target, true, 302);
    return true;
}

if ($uriPath === '/consult-light' || $uriPath === '/consult-light/' || $uriPath === '/en/consult-light' || $uriPath === '/en/consult-light/') {
    $originalQuery = parse_url($_SERVER['REQUEST_URI'] ?? '', PHP_URL_QUERY);
    $target = '/?open=consult-light';
    if (is_string($originalQuery) && $originalQuery !== '') {
        $target .= '&' . $originalQuery;
    }
    header('Location: ' . $target, true, 302);
    return true;
}

$trimmed = trim($uriPath, '/');
// /en/<page> serves the same template; includes/i18n.php reads the language
// back off the URL, so the prefix only needs stripping to find the file.
if (str_starts_with($trimmed, 'en/')) {
    $trimmed = substr($trimmed, 3);
}
if ($trimmed !== '' && preg_match('/^[A-Za-z0-9-]+$/', $trimmed) === 1) {
    $phpPage = $root . '/' . $trimmed . '.php';
    if (is_file($phpPage)) {
        require $phpPage;
        return true;
    }
}

http_response_code(404);
echo 'Not Found';
