<?php

declare(strict_types=1);

// Every page gets the same search-engine block. It is appended after the page
// list below rather than written out seven times, and always lands last so it
// never pushes the actual page copy down the section tabs.
$seoSection = static function (string $descriptionLabel): array {
    return [
        'label' => 'Search engine listing',
        'fields' => [
            ['key' => 'title', 'label' => 'Title shown in Google and the browser tab (about 60 characters)', 'type' => 'text', 'counter' => 60],
            ['key' => 'description', 'label' => $descriptionLabel, 'type' => 'richtext', 'counter' => 155],
            ['key' => 'shareImage', 'label' => 'Image shown when the page is shared on social media (1200 x 630 pixels works best)', 'type' => 'image'],
            ['key' => 'noindex', 'label' => 'Hide this page from Google', 'type' => 'toggle'],
        ],
    ];
};

$pages = [
    'home' => [
        'label' => 'Homepage',
        'sections' => [
            'hero' => [
                'label' => 'Hero',
                'fields' => [
                    ['key' => 'eyebrow', 'label' => 'Eyebrow line', 'type' => 'text'],
                    ['key' => 'headline1', 'label' => 'Headline — line 1', 'type' => 'text'],
                    ['key' => 'headline2', 'label' => 'Headline — line 2', 'type' => 'text'],
                    ['key' => 'sub', 'label' => 'Subtext', 'type' => 'richtext'],
                    ['key' => 'ctaPrimary', 'label' => 'Primary button', 'type' => 'text'],
                    ['key' => 'ctaSecondary', 'label' => 'Secondary button', 'type' => 'text'],
                    ['key' => 'mobileVideo', 'label' => 'Hero video (mobile)', 'type' => 'video'],
                    ['key' => 'desktopVideo', 'label' => 'Hero video (desktop)', 'type' => 'video'],
                    ['key' => 't1', 'label' => 'Persönliche Beratung in Österreich, Behandlung in unserer führenden Kl', 'type' => 'richtext'],
                    ['key' => 't2', 'label' => 'Individuelles Haarlinien-Design', 'type' => 'text'],
                    ['key' => 't3', 'label' => 'Stressfreie Sedierung', 'type' => 'text'],
                    ['key' => 't4', 'label' => '360°-Betreuung', 'type' => 'text'],
                    ['key' => 't5', 'label' => 'Beratung bis Nachsorge', 'type' => 'text'],
                    ['key' => 't6', 'label' => 'Google-Bewertungen', 'type' => 'text'],
                ],
                'list' => ['key' => 'trustPills', 'label' => 'Trust pills', 'itemType' => 'text'],
            ],
            'trustBar' => [
                'label' => 'Trust bar (stat strip)',
                'fields' => [
                    ['key' => 'stat1Label', 'label' => 'Stat 1 label (under patient count)', 'type' => 'text'],
                    ['key' => 'stat2Label', 'label' => 'Stat 2 label (under review score)', 'type' => 'text'],
                    ['key' => 'stat3Unit', 'label' => 'Stat 3 unit (e.g. "Years")', 'type' => 'text'],
                    ['key' => 'stat3Label', 'label' => 'Stat 3 label (under years)', 'type' => 'text'],
                    ['key' => 'stat4Main', 'label' => 'Stat 4 main text (e.g. "Largest Network")', 'type' => 'text'],
                    ['key' => 'stat4Label', 'label' => 'Stat 4 label', 'type' => 'text'],
                ],
            ],
            'promise' => [
                'label' => 'Promise / 360° care section',
                'fields' => [
                    ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'],
                    ['key' => 'sub', 'label' => 'Subtext', 'type' => 'richtext'],
                    ['key' => 'video', 'label' => 'Background video', 'type' => 'video'],
                ],
            ],
            'beforeAfter' => [
                'label' => 'Before & after (Vorher/Nachher carousel)',
                'fields' => [
                    ['key' => 'heading1', 'label' => 'Heading (line 1)', 'type' => 'text'],
                    ['key' => 'heading2', 'label' => 'Heading (line 2, highlighted)', 'type' => 'text'],
                    ['key' => 'sub', 'label' => 'Subtext', 'type' => 'richtext'],
                    ['key' => 't1', 'label' => 'Vorher &amp; Nachher', 'type' => 'text'],
                    ['key' => 't2', 'label' => 'VORHER', 'type' => 'text'],
                    ['key' => 't3', 'label' => 'Kopfhaut-Analyse', 'type' => 'text'],
                    ['key' => 't4', 'label' => 'NACHHER', 'type' => 'text'],
                    ['key' => 't5', 'label' => 'Präzises Ergebnis', 'type' => 'text'],
                    ['key' => 't6', 'label' => 'Mit Erfahrung gestaltet', 'type' => 'text'],
                    ['key' => 't7', 'label' => 'Für maximale Präzision', 'type' => 'text'],
                    ['key' => 't8', 'label' => 'Natürliche Dichte', 'type' => 'text'],
                    ['key' => 't9', 'label' => 'Für ein echtes Ergebnis', 'type' => 'text'],
                    ['key' => 't10', 'label' => 'Individuell geplant', 'type' => 'text'],
                    ['key' => 't11', 'label' => 'Für langfristige Erfolge', 'type' => 'text'],
                    ['key' => 't12', 'label' => 'Jetzt kostenlose Beratung sichern', 'type' => 'text'],
                ],
                'list' => ['key' => 'cases', 'label' => 'Cases', 'itemType' => 'fields', 'itemFields' => [['key' => 'vorherImage', 'label' => 'Vorher photo', 'type' => 'image'], ['key' => 'vorherImageAlt', 'label' => 'Vorher photo: image description (alt text)', 'type' => 'text'], ['key' => 'vorherLine1', 'label' => 'Vorher (line 1)', 'type' => 'text'], ['key' => 'vorherLine2', 'label' => 'Vorher (line 2)', 'type' => 'text'], ['key' => 'nachherImage', 'label' => 'Nachher photo', 'type' => 'image'], ['key' => 'nachherImageAlt', 'label' => 'Nachher photo: image description (alt text)', 'type' => 'text'], ['key' => 'nachherLine1', 'label' => 'Nachher (line 1)', 'type' => 'text'], ['key' => 'nachherLine2', 'label' => 'Nachher (line 2)', 'type' => 'text']]],
            ],
            'network' => [
                'label' => 'Aftercare network section',
                'fields' => [
                    ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'],
                    ['key' => 'sub', 'label' => 'Subtext', 'type' => 'richtext'],
                    ['key' => 't1', 'label' => 'Unser Netzwerk', 'type' => 'text'],
                    ['key' => 't2', 'label' => 'Nachsorge', 'type' => 'text'],
                    ['key' => 't3', 'label' => 'München, Teil unseres Nachsorge-Netzwerks.', 'type' => 'text'],
                    ['key' => 't4', 'label' => 'Nachsorge', 'type' => 'text'],
                    ['key' => 't5', 'label' => 'Zürich, Teil unseres Nachsorge-Netzwerks.', 'type' => 'text'],
                    ['key' => 't6', 'label' => 'Beratung &amp; Zentrale', 'type' => 'text'],
                    ['key' => 't7', 'label' => 'Linz, Ihr erstes Gespräch findet hier statt, persönlich vor Ort.', 'type' => 'richtext'],
                    ['key' => 't8', 'label' => 'Hauptklinik', 'type' => 'text'],
                    ['key' => 't9', 'label' => 'Istanbul, Ihre Behandlung findet hier statt, mit 24/7-Betreuung.', 'type' => 'richtext'],
                    ['key' => 't10', 'label' => 'Live verbundenes Betreuungsnetzwerk', 'type' => 'text'],
                ],
            ],
            'faq' => [
                'label' => 'FAQ',
                'fields' => [
                    ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'],
                    ['key' => 't1', 'label' => 'Fragen &amp; Antworten', 'type' => 'text'],
                    ['key' => 't2', 'label' => 'Die Fragen, die potenzielle Patienten am häufigsten davon abhalten, ei', 'type' => 'richtext'],
                    ['key' => 't3', 'label' => 'Mehr über die Haartransplantation erfahren →', 'type' => 'text'],
                    ['key' => 't4', 'label' => 'Wird man sehen, dass ich eine Transplantation hatte?', 'type' => 'richtext'],
                    ['key' => 't5', 'label' => 'In den ersten 1 bis 2 Wochen können Krusten und Rötungen sichtbar sein', 'type' => 'richtext'],
                    ['key' => 't6', 'label' => 'Wie viele Grafts brauche ich?', 'type' => 'text'],
                    ['key' => 't7', 'label' => 'Das hängt vom Ausmaß des Haarausfalls und der gewünschten Dichte ab. E', 'type' => 'richtext'],
                    ['key' => 't8', 'label' => 'Ist das Ergebnis dauerhaft?', 'type' => 'text'],
                    ['key' => 't9', 'label' => 'Transplantiertes Haar stammt aus dem DHT-resistenten Spenderbereich un', 'type' => 'richtext'],
                    ['key' => 't10', 'label' => 'Was passiert, wenn das Ergebnis nicht ausreicht?', 'type' => 'richtext'],
                    ['key' => 't11', 'label' => 'Die Graft-Überlebensrate liegt bei seriösen Kliniken bei 90 bis 95%. B', 'type' => 'richtext'],
                    ['key' => 't12', 'label' => 'Können Frauen eine Haartransplantation bekommen?', 'type' => 'richtext'],
                    ['key' => 't13', 'label' => 'Ja. Frauen mit androgenetischer Alopezie können geeignete Kandidatinne', 'type' => 'richtext'],
                    ['key' => 't14', 'label' => 'Wie läuft die Anreise nach Istanbul ab?', 'type' => 'text'],
                    ['key' => 't15', 'label' => 'Apex Beauty organisiert die gesamte Logistik für Patienten aus Österre', 'type' => 'richtext'],
                    ['key' => 't16', 'label' => 'Was unterscheidet Apex direkt von einem Vermittler?', 'type' => 'richtext'],
                    ['key' => 't17', 'label' => 'Ein Vermittler koordiniert zwischen Patient und Klinik, ist aber mediz', 'type' => 'richtext'],
                    ['key' => 't18', 'label' => 'Kostenlose Beratung', 'type' => 'text'],
                    ['key' => 't19', 'label' => 'Füllen Sie das Formular aus, wir melden uns innerhalb von 24 Stunden.', 'type' => 'richtext'],
                    ['key' => 't20', 'label' => 'Info', 'type' => 'text'],
                    ['key' => 't21', 'label' => 'Bedarf', 'type' => 'text'],
                    ['key' => 't22', 'label' => 'Fotos', 'type' => 'text'],
                    ['key' => 't23', 'label' => 'Holen Sie sich Ihre kostenlose Haaranalyse', 'type' => 'text'],
                    ['key' => 't24', 'label' => 'Unser Expertenteam meldet sich innerhalb von 24 Stunden', 'type' => 'richtext'],
                    ['key' => 't25', 'label' => 'Vollständiger Name *', 'type' => 'text'],
                    ['key' => 't26', 'label' => 'E-Mail *', 'type' => 'text'],
                    ['key' => 't27', 'label' => 'Land *', 'type' => 'text'],
                    ['key' => 't28', 'label' => 'Telefon *', 'type' => 'text'],
                    ['key' => 't29', 'label' => 'Weiter', 'type' => 'text'],
                    ['key' => 't30', 'label' => 'Ihr Geschlecht *', 'type' => 'text'],
                    ['key' => 't31', 'label' => 'Männlich', 'type' => 'text'],
                    ['key' => 't32', 'label' => 'Weiblich', 'type' => 'text'],
                    ['key' => 't33', 'label' => 'Verfahren, die Sie interessieren *', 'type' => 'text'],
                    ['key' => 't34', 'label' => 'Haartransplantation', 'type' => 'text'],
                    ['key' => 't35', 'label' => 'Barttransplantation', 'type' => 'text'],
                    ['key' => 't36', 'label' => 'Augenbrauentransplantation', 'type' => 'text'],
                    ['key' => 't37', 'label' => 'Unterstützende Therapien', 'type' => 'text'],
                    ['key' => 't38', 'label' => 'PRP-Therapie', 'type' => 'text'],
                    ['key' => 't39', 'label' => 'Stammzelltherapie', 'type' => 'text'],
                    ['key' => 't40', 'label' => 'Exosom-Therapie', 'type' => 'text'],
                    ['key' => 't41', 'label' => 'Hyperbarer Sauerstoff', 'type' => 'text'],
                    ['key' => 't42', 'label' => 'Wann planen Sie den Eingriff?', 'type' => 'text'],
                    ['key' => 't43', 'label' => 'Diesen Monat', 'type' => 'text'],
                    ['key' => 't44', 'label' => 'In 1–3 Monaten', 'type' => 'text'],
                    ['key' => 't45', 'label' => 'In 3–6 Monaten', 'type' => 'text'],
                    ['key' => 't46', 'label' => 'In 6+ Monaten', 'type' => 'text'],
                    ['key' => 't47', 'label' => 'Nur recherchieren', 'type' => 'text'],
                    ['key' => 't48', 'label' => 'Zusätzliche Notizen (optional)', 'type' => 'text'],
                    ['key' => 't49', 'label' => 'Zurück', 'type' => 'text'],
                    ['key' => 't50', 'label' => 'Weiter', 'type' => 'text'],
                    ['key' => 't51', 'label' => '📸 Fotos sind optional. Unsere Experten kontaktieren Sie in jedem Fall.', 'type' => 'richtext'],
                    ['key' => 't52', 'label' => 'Vorne', 'type' => 'text'],
                    ['key' => 't53', 'label' => 'Gesicht sichtbar', 'type' => 'text'],
                    ['key' => 't54', 'label' => 'Oben', 'type' => 'text'],
                    ['key' => 't55', 'label' => 'Von oben', 'type' => 'text'],
                    ['key' => 't56', 'label' => 'Seite', 'type' => 'text'],
                    ['key' => 't57', 'label' => 'Profil', 'type' => 'text'],
                    ['key' => 't58', 'label' => 'Spender', 'type' => 'text'],
                    ['key' => 't59', 'label' => 'Hinterkopf', 'type' => 'text'],
                    ['key' => 't60', 'label' => 'Fotos hochgeladen', 'type' => 'text'],
                    ['key' => 't61', 'label' => 'Rabattgutschein (optional)', 'type' => 'text'],
                    ['key' => 't62', 'label' => 'Ich möchte über Aktionen und Angebote informiert werden.', 'type' => 'richtext'],
                    ['key' => 't63', 'label' => '🇪🇺 DSGVO · Ihre Daten sind geschützt', 'type' => 'text'],
                    ['key' => 't64', 'label' => 'Zurück', 'type' => 'text'],
                    ['key' => 't65', 'label' => 'Absenden', 'type' => 'text'],
                    ['key' => 't66', 'label' => 'Vielen Dank!', 'type' => 'text'],
                    ['key' => 't67', 'label' => 'Ihre Anfrage ist bei uns eingegangen. Unser Team meldet sich innerhalb', 'type' => 'richtext'],
                ],
                'list' => ['key' => 'items', 'label' => 'Questions', 'itemType' => 'fields', 'itemFields' => [['key' => 'question', 'label' => 'Question', 'type' => 'text'], ['key' => 'answer', 'label' => 'Answer', 'type' => 'richtext']]],
            ],
            'intro' => [
                'label' => 'intro',
                'fields' => [
                    ['key' => 't1', 'label' => 'Beratung – Vor Ort, Österreich', 'type' => 'text'],
                    ['key' => 't2', 'label' => 'Reise in die Türkei – Wir organisieren alles', 'type' => 'text'],
                    ['key' => 't3', 'label' => 'Behandlung – Hauptklinik Türkei', 'type' => 'text'],
                    ['key' => 't4', 'label' => 'Größtes Nachsorge-Netzwerk – AT·DE·CH', 'type' => 'text'],
                    ['key' => 't5', 'label' => 'Beratung – Vor Ort, Österreich', 'type' => 'text'],
                    ['key' => 't6', 'label' => 'Reise in die Türkei – Wir organisieren alles', 'type' => 'text'],
                    ['key' => 't7', 'label' => 'Behandlung – Hauptklinik Türkei', 'type' => 'text'],
                    ['key' => 't8', 'label' => 'Größtes Nachsorge-Netzwerk – AT·DE·CH', 'type' => 'text'],
                ],
            ],
            'promisesection' => [
                'label' => 'promisesection',
                'fields' => [
                    ['key' => 't1', 'label' => 'Unser Versprechen', 'type' => 'text'],
                    ['key' => 't2', 'label' => 'Österreich', 'type' => 'text'],
                    ['key' => 't3', 'label' => 'Persönliche Beratung', 'type' => 'text'],
                    ['key' => 't4', 'label' => 'Ihr erstes Gespräch findet vor Ort statt, nicht per anonymem Chat. Wir', 'type' => 'richtext'],
                    ['key' => 't5', 'label' => 'Hauptklinik Istanbul', 'type' => 'text'],
                    ['key' => 't6', 'label' => 'Behandlung mit 24/7-Betreuung', 'type' => 'text'],
                    ['key' => 't7', 'label' => 'Die Transplantation findet in unserer Hauptklinik statt, mit durchgehe', 'type' => 'richtext'],
                    ['key' => 't8', 'label' => 'AT · DE · CH Netzwerk', 'type' => 'text'],
                    ['key' => 't9', 'label' => 'Nachsorge in Ihrer Nähe', 'type' => 'text'],
                    ['key' => 't10', 'label' => 'Zurück zuhause endet die Betreuung nicht: unser Kliniknetzwerk in Öste', 'type' => 'richtext'],
                    ['key' => 't11', 'label' => 'Ein Anbieter, drei Länder, ein durchgehendes Betreuungsmodell.', 'type' => 'richtext'],
                ],
            ],
        ],
    ],
    'hairpedia' => [
        'label' => 'Hairpedia',
        'sections' => [
            'hero' => ['label' => 'Hero', 'fields' => [
                ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'],
                ['key' => 'sub', 'label' => 'Subtext', 'type' => 'richtext'],
            ]
            ],
            'wasIstHaarausfall' => ['label' => '1. Was ist Haarausfall?', 'fields' => [
                ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'],
                ['key' => 'body', 'label' => 'Body text', 'type' => 'richtext'],
                ['key' => 'image', 'label' => 'Image', 'type' => 'image'],
                ['key' => 'imageAlt', 'label' => 'Image: image description (alt text)', 'type' => 'text'],
                ['key' => 't1', 'label' => 'Bildplatzhalter: Diagramm', 'type' => 'text'],
                ['key' => 't2', 'label' => 'Illustration des Haarwachstumszyklus (Anagen, Katagen, Telogen) als kr', 'type' => 'richtext'],
                ['key' => 't3', 'label' => '1–1,5 Mrd.', 'type' => 'text'],
                ['key' => 't4', 'label' => 'Menschen weltweit von androgenetischer Alopezie betroffen', 'type' => 'richtext'],
                ['key' => 't5', 'label' => '80% / 50%', 'type' => 'text'],
                ['key' => 't6', 'label' => 'der Männer bzw. Frauen zeigen bis 70 einen gewissen Grad an Haarausfal', 'type' => 'richtext'],
                ['key' => 't7', 'label' => 'Haarausfall ist nicht nur ein kosmetisches Thema. Studien zeigen durch', 'type' => 'richtext'],
                ['key' => 't8', 'label' => 'Der Haarwachstumszyklus', 'type' => 'text'],
                ['key' => 't9', 'label' => 'Jedes Haar durchläuft drei Phasen. Zu verstehen, wie sie funktionieren', 'type' => 'richtext'],
                ['key' => 't10', 'label' => 'Anagen', 'type' => 'text'],
                ['key' => 't11', 'label' => '2–7 Jahre · Wachstumsphase', 'type' => 'text'],
                ['key' => 't12', 'label' => 'Der Follikel produziert aktiv einen Haarschaft, rund 1 bis 1,5 cm pro ', 'type' => 'richtext'],
                ['key' => 't13', 'label' => 'Katagen', 'type' => 'text'],
                ['key' => 't14', 'label' => '2–3 Wochen · Übergangsphase', 'type' => 'text'],
                ['key' => 't15', 'label' => 'Eine kurze Übergangsphase. Die Haarproduktion stoppt, der Follikel sch', 'type' => 'richtext'],
                ['key' => 't16', 'label' => 'Telogen', 'type' => 'text'],
                ['key' => 't17', 'label' => '~3 Monate · Ruhephase', 'type' => 'text'],
                ['key' => 't18', 'label' => 'Der Follikel ruht rund 3 Monate. Am Ende der Phase fällt das Haar aus ', 'type' => 'richtext'],
            ]
            ],
            'ursachen' => ['label' => '2. Ursachen', 'fields' => [
                ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'],
                ['key' => 'body', 'label' => 'Body text', 'type' => 'richtext'],
                ['key' => 'image', 'label' => 'Image', 'type' => 'image'],
                ['key' => 'imageAlt', 'label' => 'Image: image description (alt text)', 'type' => 'text'],
                ['key' => 't1', 'label' => 'Bildplatzhalter: Infografik', 'type' => 'text'],
                ['key' => 't2', 'label' => 'Infografik mit Icons für jede Ursachengruppe (Genetik, Hormone, Stress', 'type' => 'richtext'],
                ['key' => 't3', 'label' => 'Häufigste Ursache', 'type' => 'text'],
                ['key' => 't4', 'label' => 'Genetik', 'type' => 'text'],
                ['key' => 't5', 'label' => 'Die genetische Veranlagung ist der Haupttreiber. Rund 80% der Männer m', 'type' => 'richtext'],
                ['key' => 't6', 'label' => 'DHT (Dihydrotestosteron)', 'type' => 'text'],
                ['key' => 't7', 'label' => 'Der zentrale Hormontreiber bei Männern und Frauen. DHT bindet an genet', 'type' => 'richtext'],
                ['key' => 't8', 'label' => 'Hormonelle Veränderungen', 'type' => 'text'],
                ['key' => 't9', 'label' => 'Schwangerschaft, Wechseljahre, Schilddrüsenerkrankungen und PCOS könne', 'type' => 'richtext'],
                ['key' => 't10', 'label' => 'Stress', 'type' => 'text'],
                ['key' => 't11', 'label' => 'Starker physischer oder psychischer Stress kann viele Follikel gleichz', 'type' => 'richtext'],
                ['key' => 't12', 'label' => 'Ernährung &amp; Mängel', 'type' => 'text'],
                ['key' => 't13', 'label' => 'Eisen, Vitamin D, Zink, Protein und Biotin sind für aktive Follikel es', 'type' => 'richtext'],
                ['key' => 't14', 'label' => 'Medikamente', 'type' => 'text'],
                ['key' => 't15', 'label' => 'Blutverdünner, Chemotherapeutika, Antidepressiva, Betablocker und horm', 'type' => 'richtext'],
                ['key' => 't16', 'label' => 'Erkrankungen', 'type' => 'text'],
                ['key' => 't17', 'label' => 'Alopecia areata, Kopfhautinfektionen, Lupus und andere Autoimmunerkran', 'type' => 'richtext'],
            ]
            ],
            'arten' => ['label' => '3. Arten von Haarausfall', 'fields' => [
                ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'],
                ['key' => 'body', 'label' => 'Body text', 'type' => 'richtext'],
                ['key' => 'image', 'label' => 'Image', 'type' => 'image'],
                ['key' => 'imageAlt', 'label' => 'Image: image description (alt text)', 'type' => 'text'],
                ['key' => 't1', 'label' => 'Bildplatzhalter: Vergleichsgrafik', 'type' => 'text'],
                ['key' => 't2', 'label' => 'Kopfumriss-Illustrationen, die die typischen Ausfallmuster jeder Art z', 'type' => 'richtext'],
                ['key' => 't3', 'label' => 'Häufigste Form', 'type' => 'text'],
                ['key' => 't4', 'label' => 'Androgenetische Alopezie', 'type' => 'text'],
                ['key' => 't5', 'label' => 'Erblich bedingter Haarausfall. Bei Männern Geheimratsecken und Scheite', 'type' => 'richtext'],
                ['key' => 't6', 'label' => 'Alopecia areata', 'type' => 'text'],
                ['key' => 't7', 'label' => 'Autoimmunerkrankung, bei der das Immunsystem Follikel angreift, meist ', 'type' => 'richtext'],
                ['key' => 't8', 'label' => 'Telogenes Effluvium', 'type' => 'text'],
                ['key' => 't9', 'label' => 'Vorübergehendes, diffuses Ausdünnen 2 bis 4 Monate nach Geburt, OP, sc', 'type' => 'richtext'],
                ['key' => 't10', 'label' => 'Traktionsalopezie', 'type' => 'text'],
                ['key' => 't11', 'label' => 'Haarausfall durch dauerhaften Zug, etwa durch enge Zöpfe, Extensions o', 'type' => 'richtext'],
                ['key' => 't12', 'label' => 'Vernarbende Alopezie', 'type' => 'text'],
                ['key' => 't13', 'label' => 'Follikel werden zerstört und durch Narbengewebe ersetzt, dauerhafter H', 'type' => 'richtext'],
            ]
            ],
            'diagnose' => ['label' => '4. Diagnose', 'fields' => [
                ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'],
                ['key' => 'body', 'label' => 'Body text', 'type' => 'richtext'],
                ['key' => 'image', 'label' => 'Image', 'type' => 'image'],
                ['key' => 'imageAlt', 'label' => 'Image: image description (alt text)', 'type' => 'text'],
                ['key' => 't1', 'label' => 'Bildplatzhalter: Klinikfoto', 'type' => 'text'],
                ['key' => 't2', 'label' => 'Foto einer Trichoskopie-Untersuchung in der Apex-Klinik', 'type' => 'richtext'],
                ['key' => 't3', 'label' => 'Klinische Untersuchung', 'type' => 'text'],
                ['key' => 't4', 'label' => 'Anamnese zu Beginn, Verlauf, Familiengeschichte, Medikamenten und Ernä', 'type' => 'richtext'],
                ['key' => 't5', 'label' => 'Bei Apex Beauty', 'type' => 'text'],
                ['key' => 't6', 'label' => 'Trichoskopie &amp; Scalp Mapping', 'type' => 'text'],
                ['key' => 't7', 'label' => 'Ein Dermatoskop vergrößert die Kopfhaut bis zu 70-fach und zeigt Folli', 'type' => 'richtext'],
                ['key' => 't8', 'label' => 'Der Zugtest', 'type' => 'text'],
                ['key' => 't9', 'label' => '40 bis 60 Haare werden sanft gezogen. Lösen sich mehr als 6, deutet da', 'type' => 'richtext'],
                ['key' => 't10', 'label' => 'Bluttests', 'type' => 'text'],
                ['key' => 't11', 'label' => 'Blutbild, Eisen und Ferritin, Schilddrüsenwerte, Hormonspiegel (Testos', 'type' => 'richtext'],
                ['key' => 't12', 'label' => 'Kopfhautbiopsie', 'type' => 'text'],
                ['key' => 't13', 'label' => 'Bei unklaren Fällen bestätigt eine kleine Gewebeprobe unter dem Mikros', 'type' => 'richtext'],
            ]
            ],
            'behandlung' => ['label' => '5. Behandlungsmöglichkeiten', 'fields' => [
                ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'],
                ['key' => 'body', 'label' => 'Body text', 'type' => 'richtext'],
                ['key' => 'image', 'label' => 'Image', 'type' => 'image'],
                ['key' => 'imageAlt', 'label' => 'Image: image description (alt text)', 'type' => 'text'],
                ['key' => 't1', 'label' => 'Bildplatzhalter: Produktfotos', 'type' => 'text'],
                ['key' => 't2', 'label' => 'Foto-Serie der Behandlungsoptionen: Minoxidil-Flasche, PRP-Kit, Mesoth', 'type' => 'richtext'],
                ['key' => 't3', 'label' => 'Minoxidil', 'type' => 'text'],
                ['key' => 't4', 'label' => 'Topisch oder oral. Verlängert die Anagen-Phase und verbessert die Durc', 'type' => 'richtext'],
                ['key' => 't5', 'label' => 'Finasterid', 'type' => 'text'],
                ['key' => 't6', 'label' => 'Orales Medikament, senkt DHT in der Kopfhaut um rund 70%. Stoppt den H', 'type' => 'richtext'],
                ['key' => 't7', 'label' => 'Dutasterid', 'type' => 'text'],
                ['key' => 't8', 'label' => 'Stärkere Alternative zu Finasterid, senkt DHT um rund 90%. Off-Label u', 'type' => 'richtext'],
                ['key' => 't9', 'label' => 'PRP', 'type' => 'text'],
                ['key' => 't10', 'label' => 'Plättchenreiches Plasma aus dem eigenen Blut wird in die Kopfhaut inji', 'type' => 'richtext'],
                ['key' => 't11', 'label' => 'Experimentell', 'type' => 'text'],
                ['key' => 't12', 'label' => 'Exosomen', 'type' => 'text'],
                ['key' => 't13', 'label' => 'Aus Stammzellen gewonnene Vesikel mit Wachstumssignalen, per Microneed', 'type' => 'richtext'],
                ['key' => 't14', 'label' => 'Mesotherapie', 'type' => 'text'],
                ['key' => 't15', 'label' => 'Mikroinjektionen aus Vitaminen, Mineralien und Wachstumsfaktoren zur U', 'type' => 'richtext'],
                ['key' => 't16', 'label' => 'Einzig dauerhafte Lösung', 'type' => 'text'],
                ['key' => 't17', 'label' => 'Haartransplantation', 'type' => 'text'],
                ['key' => 't18', 'label' => 'Die einzige Behandlung, die dauerhaft Haare in kahle oder ausgedünnte ', 'type' => 'richtext'],
            ]
            ],
            'transplantation' => ['label' => '6. Haartransplantation', 'fields' => [
                ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'],
                ['key' => 'body', 'label' => 'Body text', 'type' => 'richtext'],
                ['key' => 'image', 'label' => 'Image', 'type' => 'image'],
                ['key' => 'imageAlt', 'label' => 'Image: image description (alt text)', 'type' => 'text'],
                ['key' => 't1', 'label' => 'Bildplatzhalter: Technik-Diagramm', 'type' => 'text'],
                ['key' => 't2', 'label' => 'Schnittdarstellung von FUE, Saphir-FUE und DHI im direkten Vergleich', 'type' => 'richtext'],
                ['key' => 't3', 'label' => 'Wer ist geeignet?', 'type' => 'text'],
                ['key' => 't4', 'label' => 'Androgenetische Alopezie in einer stabilen Phase (der Ausfall hat sich', 'type' => 'richtext'],
                ['key' => 't5', 'label' => 'Ausreichende Spenderdichte an Hinterkopf und Seiten.', 'type' => 'richtext'],
                ['key' => 't6', 'label' => 'Realistische Erwartungen: eine Transplantation stellt Dichte wieder he', 'type' => 'richtext'],
                ['key' => 't7', 'label' => 'Guter allgemeiner Gesundheitszustand, keine aktiven Infektionen oder u', 'type' => 'richtext'],
                ['key' => 't8', 'label' => 'Die drei wichtigsten Techniken', 'type' => 'text'],
                ['key' => 't9', 'label' => 'FUE', 'type' => 'text'],
                ['key' => 't10', 'label' => 'Follikuläre Einheiten (1 bis 4 Haare) werden einzeln mit einem Mikro-P', 'type' => 'richtext'],
                ['key' => 't11', 'label' => 'Meistgenutzt in Istanbul', 'type' => 'text'],
                ['key' => 't12', 'label' => 'Saphir-FUE', 'type' => 'text'],
                ['key' => 't13', 'label' => 'Kanäle werden mit Saphirklingen statt Stahl geöffnet: kleinere, präzis', 'type' => 'richtext'],
                ['key' => 't14', 'label' => 'DHI', 'type' => 'text'],
                ['key' => 't15', 'label' => 'Follikel werden mit einem Choi Implanter Pen direkt implantiert, ohne ', 'type' => 'richtext'],
                ['key' => 't16', 'label' => 'Saphir-FUE oder DHI: der Vergleich', 'type' => 'text'],
                ['key' => 't17', 'label' => 'Faktor', 'type' => 'text'],
                ['key' => 't18', 'label' => 'Saphir-FUE', 'type' => 'text'],
                ['key' => 't19', 'label' => 'DHI', 'type' => 'text'],
                ['key' => 't20', 'label' => 'Am besten für', 'type' => 'text'],
                ['key' => 't21', 'label' => 'Große Flächen, hohe Graft-Zahlen', 'type' => 'text'],
                ['key' => 't22', 'label' => 'Haaransatz, hohe Detailtreue, kleinere Flächen', 'type' => 'richtext'],
                ['key' => 't23', 'label' => 'Heilung', 'type' => 'text'],
                ['key' => 't24', 'label' => 'Schnell (kleinere Schnitte)', 'type' => 'text'],
                ['key' => 't25', 'label' => 'Moderat (mehr Werkzeugdurchgänge)', 'type' => 'text'],
                ['key' => 't26', 'label' => 'Präzision', 'type' => 'text'],
                ['key' => 't27', 'label' => 'Hoch', 'type' => 'text'],
                ['key' => 't28', 'label' => 'Sehr hoch (Winkel- und Tiefenkontrolle)', 'type' => 'text'],
                ['key' => 't29', 'label' => 'Typische Sitzungsdauer', 'type' => 'text'],
                ['key' => 't30', 'label' => '5 bis 8 Stunden', 'type' => 'text'],
                ['key' => 't31', 'label' => '6 bis 10 Stunden', 'type' => 'text'],
                ['key' => 't32', 'label' => 'Relative Kosten', 'type' => 'text'],
                ['key' => 't33', 'label' => 'Moderat', 'type' => 'text'],
                ['key' => 't34', 'label' => 'Höher', 'type' => 'text'],
                ['key' => 't35', 'label' => 'Kombinierbar?', 'type' => 'text'],
                ['key' => 't36', 'label' => 'Ja', 'type' => 'text'],
                ['key' => 't37', 'label' => 'Ja, DHI für Ansatz + Saphir-FUE für Oberkopf ist gängig', 'type' => 'richtext'],
                ['key' => 't38', 'label' => 'Realistische Erwartungen', 'type' => 'text'],
                ['key' => 't39', 'label' => 'Eine Transplantation verschiebt vorhandene gesunde Follikel, sie ersch', 'type' => 'richtext'],
                ['key' => 't40', 'label' => 'Transplantiertes Haar wächst lebenslang, da es aus DHT-resistenten Zon', 'type' => 'richtext'],
                ['key' => 't41', 'label' => 'Das vollständige Ergebnis zeigt sich erst nach 12 bis 18 Monaten, nich', 'type' => 'richtext'],
            ]
            ],
            'genesung' => ['label' => '7. Genesung & Nachsorge', 'fields' => [
                ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'],
                ['key' => 'body', 'label' => 'Body text', 'type' => 'richtext'],
                ['key' => 'image', 'label' => 'Image', 'type' => 'image'],
                ['key' => 'imageAlt', 'label' => 'Image: image description (alt text)', 'type' => 'text'],
                ['key' => 't1', 'label' => 'Bildplatzhalter: Foto-Zeitstrahl', 'type' => 'text'],
                ['key' => 't2', 'label' => 'Patientenfotos von Tag 1 bis Monat 18, mit Einwilligung, den Heilungsv', 'type' => 'richtext'],
                ['key' => 't3', 'label' => 'Tag 1 bis 7', 'type' => 'text'],
                ['key' => 't4', 'label' => 'Erste Heilung', 'type' => 'text'],
                ['key' => 't5', 'label' => 'Kleine Krusten bilden sich, Rötung und leichte Schwellung um Stirn und', 'type' => 'richtext'],
                ['key' => 't6', 'label' => 'Woche 2 bis 4', 'type' => 'text'],
                ['key' => 't7', 'label' => 'Schock-Verlust', 'type' => 'text'],
                ['key' => 't8', 'label' => 'Bis zu 90% der transplantierten Haarschäfte fallen aus. Das ist völlig', 'type' => 'richtext'],
                ['key' => 't9', 'label' => 'Monat 2 bis 3', 'type' => 'text'],
                ['key' => 't10', 'label' => 'Die ruhige Phase', 'type' => 'text'],
                ['key' => 't11', 'label' => 'Kaum sichtbares Wachstum, die Follikel ruhen. Erste feine Haare können', 'type' => 'richtext'],
                ['key' => 't12', 'label' => 'Monat 3 bis 6', 'type' => 'text'],
                ['key' => 't13', 'label' => 'Sichtbares Wachstum beginnt', 'type' => 'text'],
                ['key' => 't14', 'label' => 'Feine neue Haare erscheinen und verdicken sich allmählich. Bis Monat 6', 'type' => 'richtext'],
                ['key' => 't15', 'label' => 'Monat 6 bis 9', 'type' => 'text'],
                ['key' => 't16', 'label' => 'Die Dichte verbessert sich', 'type' => 'text'],
                ['key' => 't17', 'label' => 'Das Haar wird spürbar dicker und dunkler. Rund 80% der Grafts sind zu ', 'type' => 'richtext'],
                ['key' => 't18', 'label' => 'Monat 12 bis 18', 'type' => 'text'],
                ['key' => 't19', 'label' => 'Endgültige Verfeinerung', 'type' => 'text'],
                ['key' => 't20', 'label' => 'Die letzten Haare reifen und verdicken sich. Das transplantierte Haar ', 'type' => 'richtext'],
                ['key' => 't21', 'label' => 'Die wichtigsten Nachsorgeregeln', 'type' => 'text'],
                ['key' => 't22', 'label' => 'Keine direkte Sonne auf der Kopfhaut für mindestens 4 Wochen.', 'type' => 'richtext'],
                ['key' => 't23', 'label' => 'Kein Schwimmen (Pool, Meer, See) für mindestens 4 Wochen.', 'type' => 'richtext'],
                ['key' => 't24', 'label' => 'Kein intensiver Sport oder starkes Schwitzen für 2 bis 3 Wochen.', 'type' => 'richtext'],
                ['key' => 't25', 'label' => 'Kein Alkohol in der ersten Woche, er beeinträchtigt die Durchblutung.', 'type' => 'richtext'],
                ['key' => 't26', 'label' => 'Nicht rauchen: Nikotin verengt die Blutgefäße und senkt die Graft-Über', 'type' => 'richtext'],
                ['key' => 't27', 'label' => 'Kopf erhöht schlafen für die ersten 3 bis 5 Nächte.', 'type' => 'richtext'],
                ['key' => 't28', 'label' => 'Sanft waschen nach Klinikanleitung, keinen starken Wasserstrahl direkt', 'type' => 'richtext'],
                ['key' => 't29', 'label' => 'Haare im ersten Monat nicht aggressiv schneiden, färben oder stylen.', 'type' => 'richtext'],
                ['key' => 't30', 'label' => 'Verschriebene Medikamente wie Finasterid oder Minoxidil wie angeordnet', 'type' => 'richtext'],
                ['key' => 't31', 'label' => 'Alle Folgetermine wahrnehmen, manche Kliniken bieten Remote-Check-ins ', 'type' => 'richtext'],
            ]
            ],
            'vorherNachher' => ['label' => '8. Vorher-Nachher', 'fields' => [
                ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'],
                ['key' => 'body', 'label' => 'Body text', 'type' => 'richtext'],
                ['key' => 'image', 'label' => 'Image', 'type' => 'image'],
                ['key' => 'imageAlt', 'label' => 'Image: image description (alt text)', 'type' => 'text'],
                ['key' => 't1', 'label' => 'Bildplatzhalter: Vorher-Nachher-Galerie', 'type' => 'text'],
                ['key' => 't2', 'label' => 'Echte Apex-Patientenfotos im Split-Vergleich, mit schriftlicher Einwil', 'type' => 'richtext'],
                ['key' => 't3', 'label' => 'Tag 1 bis 7', 'type' => 'text'],
                ['key' => 't4', 'label' => 'Grafts setzen sich, Blutversorgung baut sich wieder auf', 'type' => 'richtext'],
                ['key' => 't5', 'label' => 'Sichtbar: Rötung, kleine Krusten, leichte Schwellung', 'type' => 'richtext'],
                ['key' => 't6', 'label' => 'Woche 2 bis 4', 'type' => 'text'],
                ['key' => 't7', 'label' => 'Follikel treten in die Telogen-Phase ein, Schock-Verlust', 'type' => 'richtext'],
                ['key' => 't8', 'label' => 'Sichtbar: transplantiertes Haar fällt aus, das ist normal', 'type' => 'richtext'],
                ['key' => 't9', 'label' => 'Monat 2 bis 3', 'type' => 'text'],
                ['key' => 't10', 'label' => 'Follikel in Ruhephase, neuer Zyklus bereitet sich vor', 'type' => 'richtext'],
                ['key' => 't11', 'label' => 'Sichtbar: kaum Veränderung, Kopfhaut wirkt ruhig', 'type' => 'richtext'],
                ['key' => 't12', 'label' => 'Monat 3 bis 5', 'type' => 'text'],
                ['key' => 't13', 'label' => 'Neue Anagen-Phase beginnt, erste Haare erscheinen', 'type' => 'richtext'],
                ['key' => 't14', 'label' => 'Sichtbar: feine, helle Haare, rund 20% Fortschritt', 'type' => 'richtext'],
                ['key' => 't15', 'label' => 'Monat 5 bis 7', 'type' => 'text'],
                ['key' => 't16', 'label' => 'Haarschaft verdickt sich, wird dunkler und länger', 'type' => 'richtext'],
                ['key' => 't17', 'label' => 'Sichtbar: rund 50% der Enddichte', 'type' => 'text'],
                ['key' => 't18', 'label' => 'Monat 7 bis 9', 'type' => 'text'],
                ['key' => 't19', 'label' => 'Dichte, Deckung und Textur verbessern sich weiter', 'type' => 'richtext'],
                ['key' => 't20', 'label' => 'Sichtbar: rund 70 bis 80% des Endergebnisses', 'type' => 'text'],
                ['key' => 't21', 'label' => 'Monat 10 bis 12', 'type' => 'text'],
                ['key' => 't22', 'label' => 'Die meisten Grafts sind ausgereift, Endergebnis formt sich', 'type' => 'richtext'],
                ['key' => 't23', 'label' => 'Sichtbar: nahezu finales Erscheinungsbild, natürliche Verschmelzung', 'type' => 'richtext'],
                ['key' => 't24', 'label' => 'Monat 12 bis 18', 'type' => 'text'],
                ['key' => 't25', 'label' => 'Letzte Haare reifen, volle Integration mit dem natürlichen Haar', 'type' => 'richtext'],
                ['key' => 't26', 'label' => 'Sichtbar: Endergebnis, natürlich und nicht mehr zu unterscheiden', 'type' => 'richtext'],
            ]
            ],
            'glossar' => ['label' => '9. Glossar', 'fields' => [
                ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'],
                ['key' => 'body', 'label' => 'Body text', 'type' => 'richtext'],
                ['key' => 't1', 'label' => 'Alopezie', 'type' => 'text'],
                ['key' => 't2', 'label' => 'Der medizinische Begriff für Haarausfall, unabhängig von der Ursache.', 'type' => 'richtext'],
                ['key' => 't3', 'label' => 'Anagen', 'type' => 'text'],
                ['key' => 't4', 'label' => 'Die aktive Wachstumsphase des Haarzyklus, dauert 2 bis 7 Jahre.', 'type' => 'richtext'],
                ['key' => 't5', 'label' => 'Androgenetische Alopezie', 'type' => 'text'],
                ['key' => 't6', 'label' => 'Erblich bedingter, durch DHT beeinflusster Haarausfall. Die häufigste ', 'type' => 'richtext'],
                ['key' => 't7', 'label' => 'Katagen', 'type' => 'text'],
                ['key' => 't8', 'label' => 'Die kurze Übergangsphase, rund 2 bis 3 Wochen, in der der Follikel sch', 'type' => 'richtext'],
                ['key' => 't9', 'label' => 'DHI', 'type' => 'text'],
                ['key' => 't10', 'label' => 'Direkte Haarimplantation. Technik mit einem Choi Implanter Pen, der Fo', 'type' => 'richtext'],
                ['key' => 't11', 'label' => 'DHT (Dihydrotestosteron)', 'type' => 'text'],
                ['key' => 't12', 'label' => 'Ein starkes Hormon aus Testosteron, der Haupttreiber der androgenetisc', 'type' => 'richtext'],
                ['key' => 't13', 'label' => 'Spenderbereich', 'type' => 'text'],
                ['key' => 't14', 'label' => 'Der Bereich der Kopfhaut, meist Hinterkopf und Seiten, aus dem DHT-res', 'type' => 'richtext'],
                ['key' => 't15', 'label' => 'Exosomen', 'type' => 'text'],
                ['key' => 't16', 'label' => 'Winzige, aus Stammzellen gewonnene Vesikel mit Wachstumssignalen, expe', 'type' => 'richtext'],
                ['key' => 't17', 'label' => '5-Alpha-Reduktase', 'type' => 'text'],
                ['key' => 't18', 'label' => 'Das Enzym, das Testosteron in DHT umwandelt. Wird durch Finasterid und', 'type' => 'richtext'],
                ['key' => 't19', 'label' => 'Finasterid', 'type' => 'text'],
                ['key' => 't20', 'label' => 'Orales Medikament, senkt DHT in der Kopfhaut um rund 70%, indem es Typ', 'type' => 'richtext'],
                ['key' => 't21', 'label' => 'Follikuläre Einheit', 'type' => 'text'],
                ['key' => 't22', 'label' => 'Eine natürliche Gruppierung von 1 bis 4 Haaren. Bei der Transplantatio', 'type' => 'richtext'],
                ['key' => 't23', 'label' => 'FUE', 'type' => 'text'],
                ['key' => 't24', 'label' => 'Follikuläre Einheiten-Extraktion. Einzelne Follikel werden mit einem M', 'type' => 'richtext'],
                ['key' => 't25', 'label' => 'FUT', 'type' => 'text'],
                ['key' => 't26', 'label' => 'Ältere Streifenmethode: ein Hautstreifen wird entnommen und in Einheit', 'type' => 'richtext'],
                ['key' => 't27', 'label' => 'Graft', 'type' => 'text'],
                ['key' => 't28', 'label' => 'Eine bei der Transplantation verwendete follikuläre Einheit, üblicherw', 'type' => 'richtext'],
                ['key' => 't29', 'label' => 'Ludwig-Skala', 'type' => 'text'],
                ['key' => 't30', 'label' => 'Klassifikation für weiblichen Haarausfall, Grad I bis III nach Ausmaß ', 'type' => 'richtext'],
                ['key' => 't31', 'label' => 'Mesotherapie', 'type' => 'text'],
                ['key' => 't32', 'label' => 'Mikroinjektionen aus Vitaminen, Mineralien und Wachstumsfaktoren zur U', 'type' => 'richtext'],
                ['key' => 't33', 'label' => 'Miniaturisierung', 'type' => 'text'],
                ['key' => 't34', 'label' => 'Das fortschreitende Schrumpfen der Follikel durch DHT, bis der Follike', 'type' => 'richtext'],
                ['key' => 't35', 'label' => 'Minoxidil', 'type' => 'text'],
                ['key' => 't36', 'label' => 'Topisches oder orales Mittel, das die Anagen-Phase verlängert und die ', 'type' => 'richtext'],
                ['key' => 't37', 'label' => 'Norwood-Hamilton-Skala', 'type' => 'text'],
                ['key' => 't38', 'label' => 'Klassifikation für männlichen Haarausfall, Grad I bis VII nach Muster ', 'type' => 'richtext'],
                ['key' => 't39', 'label' => 'PRP', 'type' => 'text'],
                ['key' => 't40', 'label' => 'Plättchenreiches Plasma. Eigenes Blut wird zentrifugiert und in die Ko', 'type' => 'richtext'],
                ['key' => 't41', 'label' => 'Empfängerbereich', 'type' => 'text'],
                ['key' => 't42', 'label' => 'Der ausgedünnte oder kahle Bereich der Kopfhaut, in den Grafts transpl', 'type' => 'richtext'],
                ['key' => 't43', 'label' => 'Saphir-FUE', 'type' => 'text'],
                ['key' => 't44', 'label' => 'Fortgeschrittene FUE-Variante mit Saphirklingen für kleinere, präziser', 'type' => 'richtext'],
                ['key' => 't45', 'label' => 'Schock-Verlust', 'type' => 'text'],
                ['key' => 't46', 'label' => 'Vorübergehender Ausfall des transplantierten Haares 2 bis 4 Wochen nac', 'type' => 'richtext'],
                ['key' => 't47', 'label' => 'Telogen', 'type' => 'text'],
                ['key' => 't48', 'label' => 'Die Ruhephase des Haarzyklus, rund 2 bis 3 Monate. Das Haar bleibt, wä', 'type' => 'richtext'],
                ['key' => 't49', 'label' => 'Telogenes Effluvium', 'type' => 'text'],
                ['key' => 't50', 'label' => 'Vorübergehender diffuser Haarausfall, wenn viele Follikel gleichzeitig', 'type' => 'richtext'],
                ['key' => 't51', 'label' => 'Trichoskopie', 'type' => 'text'],
                ['key' => 't52', 'label' => 'Nicht-invasive Technik mit einem Dermatoskop zur Beurteilung von Folli', 'type' => 'richtext'],
                ['key' => 't53', 'label' => 'Vertex / Oberkopf', 'type' => 'text'],
                ['key' => 't54', 'label' => 'Der obere Hinterkopfbereich, oft einer der zuletzt betroffenen Bereich', 'type' => 'richtext'],
                ['key' => 't55', 'label' => 'Kostenlose Beratung sichern', 'type' => 'text'],
                ['key' => 't56', 'label' => 'Kostenlose Beratung', 'type' => 'text'],
                ['key' => 't57', 'label' => 'Füllen Sie das Formular aus, wir melden uns innerhalb von 24 Stunden.', 'type' => 'richtext'],
                ['key' => 't58', 'label' => 'Info', 'type' => 'text'],
                ['key' => 't59', 'label' => 'Bedarf', 'type' => 'text'],
                ['key' => 't60', 'label' => 'Fotos', 'type' => 'text'],
                ['key' => 't61', 'label' => 'Holen Sie sich Ihre kostenlose Haaranalyse', 'type' => 'text'],
                ['key' => 't62', 'label' => 'Unser Expertenteam meldet sich innerhalb von 24 Stunden', 'type' => 'richtext'],
                ['key' => 't63', 'label' => 'Vollständiger Name *', 'type' => 'text'],
                ['key' => 't64', 'label' => 'E-Mail *', 'type' => 'text'],
                ['key' => 't65', 'label' => 'Land *', 'type' => 'text'],
                ['key' => 't66', 'label' => 'Telefon *', 'type' => 'text'],
                ['key' => 't67', 'label' => 'Weiter', 'type' => 'text'],
                ['key' => 't68', 'label' => 'Ihr Geschlecht *', 'type' => 'text'],
                ['key' => 't69', 'label' => 'Männlich', 'type' => 'text'],
                ['key' => 't70', 'label' => 'Weiblich', 'type' => 'text'],
                ['key' => 't71', 'label' => 'Verfahren, die Sie interessieren *', 'type' => 'text'],
                ['key' => 't72', 'label' => 'Haartransplantation', 'type' => 'text'],
                ['key' => 't73', 'label' => 'Barttransplantation', 'type' => 'text'],
                ['key' => 't74', 'label' => 'Augenbrauentransplantation', 'type' => 'text'],
                ['key' => 't75', 'label' => 'Unterstützende Therapien', 'type' => 'text'],
                ['key' => 't76', 'label' => 'PRP-Therapie', 'type' => 'text'],
                ['key' => 't77', 'label' => 'Stammzelltherapie', 'type' => 'text'],
                ['key' => 't78', 'label' => 'Exosom-Therapie', 'type' => 'text'],
                ['key' => 't79', 'label' => 'Hyperbarer Sauerstoff', 'type' => 'text'],
                ['key' => 't80', 'label' => 'Wann planen Sie den Eingriff?', 'type' => 'text'],
                ['key' => 't81', 'label' => 'Diesen Monat', 'type' => 'text'],
                ['key' => 't82', 'label' => 'In 1–3 Monaten', 'type' => 'text'],
                ['key' => 't83', 'label' => 'In 3–6 Monaten', 'type' => 'text'],
                ['key' => 't84', 'label' => 'In 6+ Monaten', 'type' => 'text'],
                ['key' => 't85', 'label' => 'Nur recherchieren', 'type' => 'text'],
                ['key' => 't86', 'label' => 'Zusätzliche Notizen (optional)', 'type' => 'text'],
                ['key' => 't87', 'label' => 'Zurück', 'type' => 'text'],
                ['key' => 't88', 'label' => 'Weiter', 'type' => 'text'],
                ['key' => 't89', 'label' => '📸 Fotos sind optional. Unsere Experten kontaktieren Sie in jedem Fall.', 'type' => 'richtext'],
                ['key' => 't90', 'label' => 'Vorne', 'type' => 'text'],
                ['key' => 't91', 'label' => 'Gesicht sichtbar', 'type' => 'text'],
                ['key' => 't92', 'label' => 'Oben', 'type' => 'text'],
                ['key' => 't93', 'label' => 'Von oben', 'type' => 'text'],
                ['key' => 't94', 'label' => 'Seite', 'type' => 'text'],
                ['key' => 't95', 'label' => 'Profil', 'type' => 'text'],
                ['key' => 't96', 'label' => 'Spender', 'type' => 'text'],
                ['key' => 't97', 'label' => 'Hinterkopf', 'type' => 'text'],
                ['key' => 't98', 'label' => 'Fotos hochgeladen', 'type' => 'text'],
                ['key' => 't99', 'label' => 'Rabattgutschein (optional)', 'type' => 'text'],
                ['key' => 't100', 'label' => 'Ich möchte über Aktionen und Angebote informiert werden.', 'type' => 'richtext'],
                ['key' => 't101', 'label' => '🇪🇺 DSGVO · Ihre Daten sind geschützt', 'type' => 'text'],
                ['key' => 't102', 'label' => 'Zurück', 'type' => 'text'],
                ['key' => 't103', 'label' => 'Absenden', 'type' => 'text'],
                ['key' => 't104', 'label' => 'Vielen Dank!', 'type' => 'text'],
                ['key' => 't105', 'label' => 'Ihre Anfrage ist bei uns eingegangen. Unser Team meldet sich innerhalb', 'type' => 'richtext'],
            ]
            ],
            'hpHero' => ['label' => 'hpHero', 'fields' => [
                ['key' => 't1', 'label' => 'Wissen &amp; Aufklärung', 'type' => 'text'],
                ['key' => 't2', 'label' => 'Was ist Haarausfall', 'type' => 'text'],
                ['key' => 't3', 'label' => 'Definition, Zahlen, Wachstumszyklus', 'type' => 'text'],
                ['key' => 't4', 'label' => 'Ursachen', 'type' => 'text'],
                ['key' => 't5', 'label' => 'Genetik, DHT, Hormone, Stress', 'type' => 'text'],
                ['key' => 't6', 'label' => 'Arten', 'type' => 'text'],
                ['key' => 't7', 'label' => 'Androgenetisch, areata und mehr', 'type' => 'text'],
                ['key' => 't8', 'label' => 'Diagnose', 'type' => 'text'],
                ['key' => 't9', 'label' => 'Trichoskopie, Zugtest, Bluttests', 'type' => 'text'],
                ['key' => 't10', 'label' => 'Behandlung', 'type' => 'text'],
                ['key' => 't11', 'label' => 'Von Minoxidil bis Transplantation', 'type' => 'text'],
                ['key' => 't12', 'label' => 'Transplantation', 'type' => 'text'],
                ['key' => 't13', 'label' => 'FUE, Saphir-FUE und DHI im Vergleich', 'type' => 'text'],
                ['key' => 't14', 'label' => 'Genesung', 'type' => 'text'],
                ['key' => 't15', 'label' => 'Zeitstrahl &amp; Nachsorgeregeln', 'type' => 'text'],
                ['key' => 't16', 'label' => 'Vorher-Nachher', 'type' => 'text'],
                ['key' => 't17', 'label' => 'Was pro Monat zu erwarten ist', 'type' => 'text'],
                ['key' => 't18', 'label' => 'Glossar', 'type' => 'text'],
                ['key' => 't19', 'label' => 'Fachbegriffe einfach erklärt', 'type' => 'text'],
                ['key' => 't20', 'label' => 'Was ist Haarausfall', 'type' => 'text'],
                ['key' => 't21', 'label' => 'Ursachen', 'type' => 'text'],
                ['key' => 't22', 'label' => 'Arten', 'type' => 'text'],
                ['key' => 't23', 'label' => 'Diagnose', 'type' => 'text'],
                ['key' => 't24', 'label' => 'Behandlung', 'type' => 'text'],
                ['key' => 't25', 'label' => 'Transplantation', 'type' => 'text'],
                ['key' => 't26', 'label' => 'Genesung', 'type' => 'text'],
                ['key' => 't27', 'label' => 'Vorher-Nachher', 'type' => 'text'],
                ['key' => 't28', 'label' => 'Glossar', 'type' => 'text'],
            ]
            ],
        ],
    ],
    'service' => [
        'label' => 'Hair Transplant Service page',
        'sections' => [
            'hero' => ['label' => 'Hero', 'fields' => [
                ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'],
                ['key' => 'sub', 'label' => 'Subtext', 'type' => 'richtext'],
            ]],
            'umfasst' => ['label' => '1. Was die Behandlung umfasst', 'fields' => [
                ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'],
                ['key' => 'body', 'label' => 'Body text', 'type' => 'richtext'],
                ['key' => 't1', 'label' => 'Die drei wichtigsten Techniken', 'type' => 'text'],
                ['key' => 't2', 'label' => 'FUE', 'type' => 'text'],
                ['key' => 't3', 'label' => 'Follikuläre Einheiten (1 bis 4 Haare) werden einzeln mit einem Mikro-P', 'type' => 'richtext'],
                ['key' => 't4', 'label' => 'Meistgenutzt in Istanbul', 'type' => 'text'],
                ['key' => 't5', 'label' => 'Saphir-FUE', 'type' => 'text'],
                ['key' => 't6', 'label' => 'Kanäle werden mit Saphirklingen statt Stahl geöffnet: kleinere, präzis', 'type' => 'richtext'],
                ['key' => 't7', 'label' => 'DHI', 'type' => 'text'],
                ['key' => 't8', 'label' => 'Follikel werden mit einem Choi Implanter Pen direkt implantiert, ohne ', 'type' => 'richtext'],
                ['key' => 't9', 'label' => 'Saphir-FUE oder DHI: der Vergleich', 'type' => 'text'],
                ['key' => 't10', 'label' => 'Faktor', 'type' => 'text'],
                ['key' => 't11', 'label' => 'Saphir-FUE', 'type' => 'text'],
                ['key' => 't12', 'label' => 'DHI', 'type' => 'text'],
                ['key' => 't13', 'label' => 'Am besten für', 'type' => 'text'],
                ['key' => 't14', 'label' => 'Große Flächen, hohe Graft-Zahlen', 'type' => 'text'],
                ['key' => 't15', 'label' => 'Haaransatz, hohe Detailtreue, kleinere Flächen', 'type' => 'richtext'],
                ['key' => 't16', 'label' => 'Heilung', 'type' => 'text'],
                ['key' => 't17', 'label' => 'Schnell (kleinere Schnitte)', 'type' => 'text'],
                ['key' => 't18', 'label' => 'Moderat (mehr Werkzeugdurchgänge)', 'type' => 'text'],
                ['key' => 't19', 'label' => 'Präzision', 'type' => 'text'],
                ['key' => 't20', 'label' => 'Hoch', 'type' => 'text'],
                ['key' => 't21', 'label' => 'Sehr hoch (Winkel- und Tiefenkontrolle)', 'type' => 'text'],
                ['key' => 't22', 'label' => 'Typische Sitzungsdauer', 'type' => 'text'],
                ['key' => 't23', 'label' => '5 bis 8 Stunden', 'type' => 'text'],
                ['key' => 't24', 'label' => '6 bis 10 Stunden', 'type' => 'text'],
                ['key' => 't25', 'label' => 'Relative Kosten', 'type' => 'text'],
                ['key' => 't26', 'label' => 'Moderat', 'type' => 'text'],
                ['key' => 't27', 'label' => 'Höher', 'type' => 'text'],
                ['key' => 't28', 'label' => 'Kombinierbar?', 'type' => 'text'],
                ['key' => 't29', 'label' => 'Ja', 'type' => 'text'],
                ['key' => 't30', 'label' => 'Ja, DHI für Ansatz + Saphir-FUE für Oberkopf ist gängig', 'type' => 'richtext'],
            ]],
            'geeignet' => ['label' => '2. Wer ist geeignet', 'fields' => [
                ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'],
                ['key' => 'body', 'label' => 'Body text', 'type' => 'richtext'],
                ['key' => 't1', 'label' => 'Androgenetische Alopezie in einer stabilen Phase (der Ausfall hat sich', 'type' => 'richtext'],
                ['key' => 't2', 'label' => 'Ausreichende Spenderdichte an Hinterkopf und Seiten.', 'type' => 'richtext'],
                ['key' => 't3', 'label' => 'Realistische Erwartungen: eine Transplantation stellt Dichte wieder he', 'type' => 'richtext'],
                ['key' => 't4', 'label' => 'Guter allgemeiner Gesundheitszustand, keine aktiven Infektionen oder u', 'type' => 'richtext'],
                ['key' => 't5', 'label' => 'Frauen mit androgenetischer Alopezie können ebenfalls geeignete Kandid', 'type' => 'richtext'],
            ]],
            'genesungService' => ['label' => '3. Genesung', 'fields' => [
                ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'],
                ['key' => 'body', 'label' => 'Body text', 'type' => 'richtext'],
                ['key' => 't1', 'label' => 'Tag 1 bis 7', 'type' => 'text'],
                ['key' => 't2', 'label' => 'Erste Heilung', 'type' => 'text'],
                ['key' => 't3', 'label' => 'Kleine Krusten bilden sich, Rötung und leichte Schwellung um Stirn und', 'type' => 'richtext'],
                ['key' => 't4', 'label' => 'Woche 2 bis 4', 'type' => 'text'],
                ['key' => 't5', 'label' => 'Schock-Verlust', 'type' => 'text'],
                ['key' => 't6', 'label' => 'Bis zu 90% der transplantierten Haarschäfte fallen aus. Das ist völlig', 'type' => 'richtext'],
                ['key' => 't7', 'label' => 'Monat 3 bis 6', 'type' => 'text'],
                ['key' => 't8', 'label' => 'Sichtbares Wachstum beginnt', 'type' => 'text'],
                ['key' => 't9', 'label' => 'Feine neue Haare erscheinen und verdicken sich allmählich. Bis Monat 6', 'type' => 'richtext'],
                ['key' => 't10', 'label' => 'Monat 6 bis 9', 'type' => 'text'],
                ['key' => 't11', 'label' => 'Die Dichte verbessert sich', 'type' => 'text'],
                ['key' => 't12', 'label' => 'Das Haar wird spürbar dicker und dunkler. Rund 80% der Grafts sind zu ', 'type' => 'richtext'],
                ['key' => 't13', 'label' => 'Monat 12 bis 18', 'type' => 'text'],
                ['key' => 't14', 'label' => 'Endgültige Verfeinerung', 'type' => 'text'],
                ['key' => 't15', 'label' => 'Die letzten Haare reifen und verdicken sich. Das transplantierte Haar ', 'type' => 'richtext'],
                ['key' => 't16', 'label' => 'Die wichtigsten Nachsorgeregeln', 'type' => 'text'],
                ['key' => 't17', 'label' => 'Keine direkte Sonne auf der Kopfhaut für mindestens 4 Wochen.', 'type' => 'richtext'],
                ['key' => 't18', 'label' => 'Kein Schwimmen (Pool, Meer, See) für mindestens 4 Wochen.', 'type' => 'richtext'],
                ['key' => 't19', 'label' => 'Kein intensiver Sport oder starkes Schwitzen für 2 bis 3 Wochen.', 'type' => 'richtext'],
                ['key' => 't20', 'label' => 'Kein Alkohol in der ersten Woche, er beeinträchtigt die Durchblutung.', 'type' => 'richtext'],
                ['key' => 't21', 'label' => 'Nicht rauchen: Nikotin verengt die Blutgefäße und senkt die Graft-Über', 'type' => 'richtext'],
                ['key' => 't22', 'label' => 'Kopf erhöht schlafen für die ersten 3 bis 5 Nächte.', 'type' => 'richtext'],
                ['key' => 't23', 'label' => 'Sanft waschen nach Klinikanleitung, keinen starken Wasserstrahl direkt', 'type' => 'richtext'],
                ['key' => 't24', 'label' => 'Alle Folgetermine wahrnehmen, manche Kliniken bieten Remote-Check-ins ', 'type' => 'richtext'],
            ]],
            'ergebnisse' => ['label' => '4. Ergebnisse', 'fields' => [
                ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'],
                ['key' => 'body', 'label' => 'Body text', 'type' => 'richtext'],
                ['key' => 't1', 'label' => 'Eine Transplantation verschiebt vorhandene gesunde Follikel, sie ersch', 'type' => 'richtext'],
                ['key' => 't2', 'label' => 'Transplantiertes Haar wächst lebenslang, da es aus DHT-resistenten Zon', 'type' => 'richtext'],
                ['key' => 't3', 'label' => 'Die Graft-Überlebensrate liegt bei seriösen Kliniken bei 90 bis 95%. B', 'type' => 'richtext'],
                ['key' => 't4', 'label' => 'In den ersten 1 bis 2 Wochen können Krusten und Rötungen sichtbar sein', 'type' => 'richtext'],
                ['key' => 't5', 'label' => 'Kostenlose Beratung sichern', 'type' => 'text'],
                ['key' => 't6', 'label' => 'Kostenlose Beratung', 'type' => 'text'],
                ['key' => 't7', 'label' => 'Füllen Sie das Formular aus, wir melden uns innerhalb von 24 Stunden.', 'type' => 'richtext'],
                ['key' => 't8', 'label' => 'Info', 'type' => 'text'],
                ['key' => 't9', 'label' => 'Bedarf', 'type' => 'text'],
                ['key' => 't10', 'label' => 'Fotos', 'type' => 'text'],
                ['key' => 't11', 'label' => 'Holen Sie sich Ihre kostenlose Haaranalyse', 'type' => 'text'],
                ['key' => 't12', 'label' => 'Unser Expertenteam meldet sich innerhalb von 24 Stunden', 'type' => 'richtext'],
                ['key' => 't13', 'label' => 'Vollständiger Name *', 'type' => 'text'],
                ['key' => 't14', 'label' => 'E-Mail *', 'type' => 'text'],
                ['key' => 't15', 'label' => 'Land *', 'type' => 'text'],
                ['key' => 't16', 'label' => 'Telefon *', 'type' => 'text'],
                ['key' => 't17', 'label' => 'Weiter', 'type' => 'text'],
                ['key' => 't18', 'label' => 'Ihr Geschlecht *', 'type' => 'text'],
                ['key' => 't19', 'label' => 'Männlich', 'type' => 'text'],
                ['key' => 't20', 'label' => 'Weiblich', 'type' => 'text'],
                ['key' => 't21', 'label' => 'Verfahren, die Sie interessieren *', 'type' => 'text'],
                ['key' => 't22', 'label' => 'Haartransplantation', 'type' => 'text'],
                ['key' => 't23', 'label' => 'Barttransplantation', 'type' => 'text'],
                ['key' => 't24', 'label' => 'Augenbrauentransplantation', 'type' => 'text'],
                ['key' => 't25', 'label' => 'Unterstützende Therapien', 'type' => 'text'],
                ['key' => 't26', 'label' => 'PRP-Therapie', 'type' => 'text'],
                ['key' => 't27', 'label' => 'Stammzelltherapie', 'type' => 'text'],
                ['key' => 't28', 'label' => 'Exosom-Therapie', 'type' => 'text'],
                ['key' => 't29', 'label' => 'Hyperbarer Sauerstoff', 'type' => 'text'],
                ['key' => 't30', 'label' => 'Wann planen Sie den Eingriff?', 'type' => 'text'],
                ['key' => 't31', 'label' => 'Diesen Monat', 'type' => 'text'],
                ['key' => 't32', 'label' => 'In 1–3 Monaten', 'type' => 'text'],
                ['key' => 't33', 'label' => 'In 3–6 Monaten', 'type' => 'text'],
                ['key' => 't34', 'label' => 'In 6+ Monaten', 'type' => 'text'],
                ['key' => 't35', 'label' => 'Nur recherchieren', 'type' => 'text'],
                ['key' => 't36', 'label' => 'Zusätzliche Notizen (optional)', 'type' => 'text'],
                ['key' => 't37', 'label' => 'Zurück', 'type' => 'text'],
                ['key' => 't38', 'label' => 'Weiter', 'type' => 'text'],
                ['key' => 't39', 'label' => '📸 Fotos sind optional. Unsere Experten kontaktieren Sie in jedem Fall.', 'type' => 'richtext'],
                ['key' => 't40', 'label' => 'Vorne', 'type' => 'text'],
                ['key' => 't41', 'label' => 'Gesicht sichtbar', 'type' => 'text'],
                ['key' => 't42', 'label' => 'Oben', 'type' => 'text'],
                ['key' => 't43', 'label' => 'Von oben', 'type' => 'text'],
                ['key' => 't44', 'label' => 'Seite', 'type' => 'text'],
                ['key' => 't45', 'label' => 'Profil', 'type' => 'text'],
                ['key' => 't46', 'label' => 'Spender', 'type' => 'text'],
                ['key' => 't47', 'label' => 'Hinterkopf', 'type' => 'text'],
                ['key' => 't48', 'label' => 'Fotos hochgeladen', 'type' => 'text'],
                ['key' => 't49', 'label' => 'Rabattgutschein (optional)', 'type' => 'text'],
                ['key' => 't50', 'label' => 'Ich möchte über Aktionen und Angebote informiert werden.', 'type' => 'richtext'],
                ['key' => 't51', 'label' => '🇪🇺 DSGVO · Ihre Daten sind geschützt', 'type' => 'text'],
                ['key' => 't52', 'label' => 'Zurück', 'type' => 'text'],
                ['key' => 't53', 'label' => 'Absenden', 'type' => 'text'],
                ['key' => 't54', 'label' => 'Vielen Dank!', 'type' => 'text'],
                ['key' => 't55', 'label' => 'Ihre Anfrage ist bei uns eingegangen. Unser Team meldet sich innerhalb', 'type' => 'richtext'],
            ]],
            'hpHero' => ['label' => 'Seitenkopf', 'fields' => [
                ['key' => 't1', 'label' => 'Verfahren', 'type' => 'text'],
                ['key' => 't2', 'label' => 'Was es umfasst', 'type' => 'text'],
                ['key' => 't3', 'label' => 'Wer ist geeignet', 'type' => 'text'],
                ['key' => 't4', 'label' => 'Genesung', 'type' => 'text'],
                ['key' => 't5', 'label' => 'Ergebnisse', 'type' => 'text'],
            ]],
        ],
    ],
    'doctor' => [
        'label' => 'Doctors page',
        'sections' => [
            'profiles' => [
                'label' => 'Doctor profiles',
                'fields' => [],
                'list' => [
                    'key' => 'items',
                    'label' => 'Doctors',
                    'itemType' => 'fields',
                    'itemFields' => [
                        ['key' => 'photo', 'label' => 'Photo', 'type' => 'image'],
                        ['key' => 'photoAlt', 'label' => 'Photo: image description (alt text)', 'type' => 'text'],
                        ['key' => 'name', 'label' => 'Name', 'type' => 'text'],
                        ['key' => 'credentials', 'label' => 'Title / credentials', 'type' => 'text'],
                        ['key' => 'intro', 'label' => 'Short intro line', 'type' => 'richtext'],
                        ['key' => 'bio', 'label' => 'Biography', 'type' => 'richtext'],
                        ['key' => 'specialtiesHeading', 'label' => 'Specialties heading (e.g. "Why Dr. Burhan")', 'type' => 'text'],
                        ['key' => 'specialty1Title', 'label' => 'Specialty 1 — title', 'type' => 'text'],
                        ['key' => 'specialty1Desc', 'label' => 'Specialty 1 — description', 'type' => 'text'],
                        ['key' => 'specialty2Title', 'label' => 'Specialty 2 — title', 'type' => 'text'],
                        ['key' => 'specialty2Desc', 'label' => 'Specialty 2 — description', 'type' => 'text'],
                        ['key' => 'specialty3Title', 'label' => 'Specialty 3 — title', 'type' => 'text'],
                        ['key' => 'specialty3Desc', 'label' => 'Specialty 3 — description', 'type' => 'text'],
                    ],
                ],
            ],
        ],
    ],
    // The package prices live here rather than in prices.php so the clinic can
    // change a price without a code change. prices.php renders every price
    // from these values (cards, comparison header, comparison footer) and the
    // Apex AI knowledge base reads the same file, so a price can only ever be
    // stated in one place. The feature lists and the comparison matrix stay in
    // the template: they change rarely and are structural rather than copy.
    'prices' => [
        'label' => 'Prices page',
        'sections' => [
            'hero' => ['label' => 'Hero', 'fields' => [
                ['key' => 'eyebrow', 'label' => 'Eyebrow chip', 'type' => 'text'],
                ['key' => 'heading', 'label' => 'Headline (wrap the highlighted part in <span>)', 'type' => 'richtext'],
                ['key' => 'sub', 'label' => 'Sub-headline', 'type' => 'richtext'],
            ]],
            'showcase' => ['label' => 'Package section heading', 'fields' => [
                ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'],
                ['key' => 'sub', 'label' => 'Sub-heading', 'type' => 'richtext'],
            ]],
            'packages' => [
                'label' => 'Packages',
                'fields' => [],
                'list' => [
                    'key' => 'items',
                    'label' => 'Packages (highest price first)',
                    'itemType' => 'fields',
                    'itemFields' => [
                        ['key' => 'name', 'label' => 'Package name', 'type' => 'text'],
                        ['key' => 'price', 'label' => 'Price (write it exactly as it should appear, per language)', 'type' => 'text'],
                        ['key' => 'priceNote', 'label' => 'Line under the price', 'type' => 'text'],
                        ['key' => 'badge', 'label' => 'Badge chip', 'type' => 'text'],
                        ['key' => 'description', 'label' => 'Short description', 'type' => 'richtext'],
                    ],
                ],
            ],
            'comparison' => ['label' => 'Comparison table heading', 'fields' => [
                ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'],
                ['key' => 'sub', 'label' => 'Sub-heading', 'type' => 'richtext'],
            ]],
            'notes' => [
                'label' => 'Notes under the table',
                'fields' => [],
                'list' => [
                    'key' => 'items',
                    'label' => 'Notes',
                    'itemType' => 'fields',
                    'itemFields' => [
                        ['key' => 'title', 'label' => 'Title', 'type' => 'text'],
                        ['key' => 'body', 'label' => 'Text', 'type' => 'richtext'],
                    ],
                ],
            ],
            'cta' => ['label' => 'Closing call to action', 'fields' => [
                ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'],
                ['key' => 'sub', 'label' => 'Text', 'type' => 'richtext'],
            ]],
        ],
    ],
    'blog' => [
        'label' => 'Guide / blog page',
        'sections' => [
            // The article list itself is managed in the Blog tab; this is only
            // the wrapper copy at the top of the archive page.
            'hero' => ['label' => 'Archive header', 'fields' => [
                ['key' => 'eyebrow', 'label' => 'Eyebrow chip', 'type' => 'text'],
                ['key' => 'heading', 'label' => 'Headline (wrap the highlighted part in <span>)', 'type' => 'richtext'],
                ['key' => 'sub', 'label' => 'Sub-headline', 'type' => 'richtext'],
            ]],
            'cta' => ['label' => 'Closing call to action', 'fields' => [
                ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'],
                ['key' => 'sub', 'label' => 'Text', 'type' => 'richtext'],
                ['key' => 'button', 'label' => 'Button label', 'type' => 'text'],
            ]],
        ],
    ],
    'contact' => [
        'label' => 'Contact / consultation modal',
        'sections' => [
            'intro' => ['label' => 'Modal intro', 'fields' => [
                ['key' => 'title', 'label' => 'Title', 'type' => 'text'],
                ['key' => 'sub', 'label' => 'Subtext', 'type' => 'richtext'],
                ['key' => 't1', 'label' => 'Info', 'type' => 'text'],
                ['key' => 't2', 'label' => 'Bedarf', 'type' => 'text'],
                ['key' => 't3', 'label' => 'Fotos', 'type' => 'text'],
                ['key' => 't4', 'label' => 'Holen Sie sich Ihre kostenlose Haaranalyse', 'type' => 'text'],
                ['key' => 't5', 'label' => 'Unser Expertenteam meldet sich innerhalb von 24 Stunden', 'type' => 'richtext'],
                ['key' => 't6', 'label' => 'Vollständiger Name *', 'type' => 'text'],
                ['key' => 't7', 'label' => 'E-Mail *', 'type' => 'text'],
                ['key' => 't8', 'label' => 'Land *', 'type' => 'text'],
                ['key' => 't9', 'label' => 'Telefon *', 'type' => 'text'],
                ['key' => 't10', 'label' => 'Weiter', 'type' => 'text'],
                ['key' => 't11', 'label' => 'Ihr Geschlecht *', 'type' => 'text'],
                ['key' => 't12', 'label' => 'Männlich', 'type' => 'text'],
                ['key' => 't13', 'label' => 'Weiblich', 'type' => 'text'],
                ['key' => 't14', 'label' => 'Verfahren, die Sie interessieren *', 'type' => 'text'],
                ['key' => 't15', 'label' => 'Haartransplantation', 'type' => 'text'],
                ['key' => 't16', 'label' => 'Barttransplantation', 'type' => 'text'],
                ['key' => 't17', 'label' => 'Augenbrauentransplantation', 'type' => 'text'],
                ['key' => 't18', 'label' => 'Unterstützende Therapien', 'type' => 'text'],
                ['key' => 't19', 'label' => 'PRP-Therapie', 'type' => 'text'],
                ['key' => 't20', 'label' => 'Stammzelltherapie', 'type' => 'text'],
                ['key' => 't21', 'label' => 'Exosom-Therapie', 'type' => 'text'],
                ['key' => 't22', 'label' => 'Hyperbarer Sauerstoff', 'type' => 'text'],
                ['key' => 't23', 'label' => 'Wann planen Sie den Eingriff?', 'type' => 'text'],
                ['key' => 't24', 'label' => 'Diesen Monat', 'type' => 'text'],
                ['key' => 't25', 'label' => 'In 1–3 Monaten', 'type' => 'text'],
                ['key' => 't26', 'label' => 'In 3–6 Monaten', 'type' => 'text'],
                ['key' => 't27', 'label' => 'In 6+ Monaten', 'type' => 'text'],
                ['key' => 't28', 'label' => 'Nur recherchieren', 'type' => 'text'],
                ['key' => 't29', 'label' => 'Zusätzliche Notizen (optional)', 'type' => 'text'],
                ['key' => 't30', 'label' => 'Zurück', 'type' => 'text'],
                ['key' => 't31', 'label' => 'Weiter', 'type' => 'text'],
                ['key' => 't32', 'label' => '📸 Fotos sind optional. Unsere Experten kontaktieren Sie in jedem Fall.', 'type' => 'richtext'],
                ['key' => 't33', 'label' => 'Vorne', 'type' => 'text'],
                ['key' => 't34', 'label' => 'Gesicht sichtbar', 'type' => 'text'],
                ['key' => 't35', 'label' => 'Oben', 'type' => 'text'],
                ['key' => 't36', 'label' => 'Von oben', 'type' => 'text'],
                ['key' => 't37', 'label' => 'Seite', 'type' => 'text'],
                ['key' => 't38', 'label' => 'Profil', 'type' => 'text'],
                ['key' => 't39', 'label' => 'Spender', 'type' => 'text'],
                ['key' => 't40', 'label' => 'Hinterkopf', 'type' => 'text'],
                ['key' => 't41', 'label' => 'Fotos hochgeladen', 'type' => 'text'],
                ['key' => 't42', 'label' => 'Rabattgutschein (optional)', 'type' => 'text'],
                ['key' => 't43', 'label' => 'Ich möchte über Aktionen und Angebote informiert werden.', 'type' => 'richtext'],
                ['key' => 't44', 'label' => '🇪🇺 DSGVO · Ihre Daten sind geschützt', 'type' => 'text'],
                ['key' => 't45', 'label' => 'Zurück', 'type' => 'text'],
                ['key' => 't46', 'label' => 'Absenden', 'type' => 'text'],
                ['key' => 't47', 'label' => 'Vielen Dank!', 'type' => 'text'],
                ['key' => 't48', 'label' => 'Ihre Anfrage ist bei uns eingegangen. Unser Team meldet sich innerhalb', 'type' => 'richtext'],
            ]
            ],
        ],
    ],
    'privacy' => [
        'label' => 'Privacy policy',
        'sections' => [
            'intro' => ['label' => 'Page intro', 'fields' => [
                ['key' => 'title', 'label' => 'Title', 'type' => 'text'],
                ['key' => 'sub', 'label' => 'Subtext', 'type' => 'richtext'],
            ]],
            'sections' => [
                'label' => 'Legal sections',
                'fields' => [],
                'list' => [
                    'key' => 'items',
                    'label' => 'Sections',
                    'itemType' => 'fields',
                    'itemFields' => [
                        ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'],
                        ['key' => 'body', 'label' => 'Body text', 'type' => 'richtext'],
                    ],
                ],
            ],
        ],
    ],
];

foreach ($pages as $pageKey => $page) {
    $pages[$pageKey]['sections']['seo'] = $seoSection(
        $pageKey === 'prices'
            ? 'Description shown under the title in Google (about 155 characters). Leave {range} in the text to keep the live price range in it.'
            : 'Description shown under the title in Google (about 155 characters)'
    );
}

return $pages;
